# Basic PyTorch

## 1. Import and use

In [55]:
# Import Toch and check version

import torch
print(torch.__version__)

import numpy as np
print(np.__version__)


1.4.0+cpu
1.18.2


## 2. Create tensors

In [4]:
# Create 1D tensor

a = torch.tensor([2, 2, 1])
print(a)

tensor([2, 2, 1])


In [14]:
# Create 2D tensor

b = torch.tensor([
    [2, 1, 4],
    [3, 5, 4],
    [1, 2, 0],
    [4, 3, 2]
    ])

print(b)

tensor([[2, 1, 4],
        [3, 5, 4],
        [1, 2, 0],
        [4, 3, 2]])


In [25]:
# Making tensors withnon-integer real numbers
# setting dtype = float or double
c = torch.tensor([
    [2, 1, 4],
    [3, 5, 4],
    [1, 2, 0],
    [4, 3, 2]
    ], dtype=torch.float)

print(c, c.dtype)

tensor([[2., 1., 4.],
        [3., 5., 4.],
        [1., 2., 0.],
        [4., 3., 2.]]) torch.float32


## 3. Play with shape and size

In [15]:
# Size and shape of tensors

print("Size and shape of a: ", a.size(), " ", a.shape)
print("Size and shape of b: ", b.size(), " ", b.shape)

Size and shape of a:  torch.Size([3])   torch.Size([3])
Size and shape of b:  torch.Size([4, 3])   torch.Size([4, 3])


In [16]:
# Rows and columns in a tensor

print("Rows and columns of b: ", b.shape[0], " ", b.shape[1])

Rows and columns of b:  4   3


In [24]:
# Reshaping array

b1 = b.view(-1, 2)  # Auto infer row, col = 2
print("b1(?, 2)", b1)

b2 = b.view(-1)  # Make no row, auto infer col 
print("b2(?)", b2) 

b3 = b.view(1, -1)  # Make 1 row, auto infer col
print("b3(1, ?)", b3) 

b4 = b.view(-1, 1)  # Auto infer row, col = 1
print("b4(?, 1)", b4) 

b1(?, 2) tensor([[2, 1],
        [4, 3],
        [5, 4],
        [1, 2],
        [0, 4],
        [3, 2]])
b2(?) tensor([2, 1, 4, 3, 5, 4, 1, 2, 0, 4, 3, 2])
b3(1, ?) tensor([[2, 1, 4, 3, 5, 4, 1, 2, 0, 4, 3, 2]])
b4(?, 1) tensor([[2],
        [1],
        [4],
        [3],
        [5],
        [4],
        [1],
        [2],
        [0],
        [4],
        [3],
        [2]])


## 4. Make tensors of specific type

In [29]:
# Create a random 2D tensor

r1 = torch.rand(3, 4)
print(r1.dtype, r1)

torch.float32 tensor([[0.2151, 0.7303, 0.6890, 0.8175],
        [0.0190, 0.1894, 0.6280, 0.4389],
        [0.2035, 0.4016, 0.1507, 0.0267]])


In [43]:
# Create a random 2D tensor from a N(0,1)

r2 = torch.rand(3, 4)
print(r2.dtype, r2)

torch.float32 tensor([[0.9898, 0.2426, 0.4915, 0.7938],
        [0.8542, 0.6184, 0.1077, 0.8109],
        [0.8584, 0.2856, 0.0615, 0.0022]])


In [37]:
# Create a random 3D tensor from a N(0,1)

r3 = torch.rand(2, 3, 4)
print(r3.dtype, r3)

torch.float32 tensor([[[0.2100, 0.9113, 0.4857, 0.9741],
         [0.4527, 0.9643, 0.8478, 0.3518],
         [0.5212, 0.1247, 0.9733, 0.2024]],

        [[0.1366, 0.5560, 0.5364, 0.7538],
         [0.7289, 0.3478, 0.9708, 0.7126],
         [0.4414, 0.8400, 0.7235, 0.2853]]])


In [34]:
# Create int array from a given range, of a given size

i1 = torch.randint(6, 10, (5,))  # 10 is excluded
print(i1.dtype, i1)

i2 = torch.randint(6, 10, (2,3))
print(i2.dtype, i2)

torch.int64 tensor([7, 8, 6, 8, 7])
torch.int64 tensor([[6, 8, 8],
        [8, 7, 7]])


In [35]:
# Create a Zeros matrix

z = torch.zeros(2, 3)
print(z)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [36]:
# Create a Ones matrix

o = torch.ones(2, 3)
print(o)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [41]:
# Create a tensor like the size of another tensor, of a give data type

r2_la = torch.rand_like(r2, dtype=torch.double)
print(r2_la)

tensor([[0.9087, 0.8084, 0.5388, 0.1632],
        [0.3659, 0.9269, 0.0478, 0.7144],
        [0.0718, 0.9268, 0.6613, 0.7611]], dtype=torch.float64)


## 5. Slicing tensors

In [49]:
rs = torch.rand(3, 3)
print(rs)

# All row, col index 1
rs1 = rs[:,1]
print(rs1, rs1.shape)

# All row, col index 1 while keeping the "shape"
rs2 = rs[:,1:2]
print(rs2, rs2.shape)


# All col, row index 2
print(rs[2,:])

# Row index 1-2, col index 0-1
print(rs[1:, :2])

tensor([[0.8817, 0.7901, 0.3299],
        [0.9962, 0.7578, 0.6344],
        [0.0666, 0.1827, 0.2787]])
tensor([0.7901, 0.7578, 0.1827]) torch.Size([3])
tensor([[0.7901],
        [0.7578],
        [0.1827]]) torch.Size([3, 1])
tensor([0.0666, 0.1827, 0.2787])
tensor([[0.9962, 0.7578],
        [0.0666, 0.1827]])


## 6. Extracting element

In [50]:
# Pick up a tensor element
rs_tensor = rs[1,1]
print(rs_tensor)

# Extract number out of that tensor
rs_number = rs_tensor.item()
print(rs_number)

tensor(0.7578)
0.7577734589576721


## 7. NumPy - PyTorch - List interconversion

In [59]:
# Make list
l_a = [1, 2, 3]
l_b = [[1, 2], [3, 4]]

print(l_a, type(l_a))
print(l_b, type(l_b))

# Convert list to tensor
t_a = torch.tensor(l_a)
t_b = torch.tensor(l_b)

print(t_a, type(t_a))
print(t_b, type(t_b))

# Convert tensor to numpy
n_a = t_a.numpy()
n_b = t_b.numpy()

print(n_a, type(n_a))
print(n_b, type(n_b))

# Convert numpy to tensor
t2_a = torch.from_numpy(n_a)
t2_b = torch.from_numpy(n_b)

print(t2_a, type(t2_a))
print(t2_b, type(t2_b))

# Convert tensor to list
l2_a = t2_a.tolist()
l2_b = t2_b.tolist()

print(l2_a, type(l2_a))
print(l2_b, type(l2_b))

[1, 2, 3] <class 'list'>
[[1, 2], [3, 4]] <class 'list'>
tensor([1, 2, 3]) <class 'torch.Tensor'>
tensor([[1, 2],
        [3, 4]]) <class 'torch.Tensor'>
[1 2 3] <class 'numpy.ndarray'>
[[1 2]
 [3 4]] <class 'numpy.ndarray'>
tensor([1, 2, 3]) <class 'torch.Tensor'>
tensor([[1, 2],
        [3, 4]]) <class 'torch.Tensor'>
[1, 2, 3] <class 'list'>
[[1, 2], [3, 4]] <class 'list'>
