# Basic PyTorch

## 1. Import and use

In [2]:
# Import Toch and check version

import torch
print(torch.__version__)

import numpy as np
print(np.__version__)


1.4.0+cpu
1.18.2


## 2. Create tensors

In [3]:
# Create 1D tensor

a = torch.tensor([2, 2, 1])
print(a)

tensor([2, 2, 1])


In [4]:
# Create 2D tensor

b = torch.tensor([
    [2, 1, 4],
    [3, 5, 4],
    [1, 2, 0],
    [4, 3, 2]
    ])

print(b)

tensor([[2, 1, 4],
        [3, 5, 4],
        [1, 2, 0],
        [4, 3, 2]])


In [5]:
# Making tensors withnon-integer real numbers
# setting dtype = float or double
c = torch.tensor([
    [2, 1, 4],
    [3, 5, 4],
    [1, 2, 0],
    [4, 3, 2]
    ], dtype=torch.float)

print(c, c.dtype)

tensor([[2., 1., 4.],
        [3., 5., 4.],
        [1., 2., 0.],
        [4., 3., 2.]]) torch.float32


## 3. Play with shape and size

In [6]:
# Size and shape of tensors

print("Size and shape of a: ", a.size(), " ", a.shape)
print("Size and shape of b: ", b.size(), " ", b.shape)

Size and shape of a:  torch.Size([3])   torch.Size([3])
Size and shape of b:  torch.Size([4, 3])   torch.Size([4, 3])


In [7]:
# Rows and columns in a tensor

print("Rows and columns of b: ", b.shape[0], " ", b.shape[1])

Rows and columns of b:  4   3


In [8]:
# Reshaping array

b1 = b.view(-1, 2)  # Auto infer row, col = 2
print("b1(?, 2)", b1)

b2 = b.view(-1)  # Make no row, auto infer col 
print("b2(?)", b2) 

b3 = b.view(1, -1)  # Make 1 row, auto infer col
print("b3(1, ?)", b3) 

b4 = b.view(-1, 1)  # Auto infer row, col = 1
print("b4(?, 1)", b4) 

b1(?, 2) tensor([[2, 1],
        [4, 3],
        [5, 4],
        [1, 2],
        [0, 4],
        [3, 2]])
b2(?) tensor([2, 1, 4, 3, 5, 4, 1, 2, 0, 4, 3, 2])
b3(1, ?) tensor([[2, 1, 4, 3, 5, 4, 1, 2, 0, 4, 3, 2]])
b4(?, 1) tensor([[2],
        [1],
        [4],
        [3],
        [5],
        [4],
        [1],
        [2],
        [0],
        [4],
        [3],
        [2]])


## 4. Make tensors of specific type

In [9]:
# Create a random 2D tensor

r1 = torch.rand(3, 4)
print(r1.dtype, r1)

torch.float32 tensor([[0.9061, 0.1461, 0.7432, 0.3904],
        [0.2357, 0.8778, 0.7968, 0.0709],
        [0.8241, 0.4513, 0.8280, 0.9439]])


In [10]:
# Create a random 2D tensor from a N(0,1)

r2 = torch.rand(3, 4)
print(r2.dtype, r2)

torch.float32 tensor([[0.0077, 0.5275, 0.8229, 0.1207],
        [0.6937, 0.3650, 0.8680, 0.6750],
        [0.4006, 0.1397, 0.4023, 0.2447]])


In [11]:
# Create a random 3D tensor from a N(0,1)

r3 = torch.rand(2, 3, 4)
print(r3.dtype, r3)

torch.float32 tensor([[[0.6827, 0.4841, 0.7020, 0.2331],
         [0.0310, 0.4937, 0.5528, 0.7902],
         [0.3664, 0.7185, 0.3187, 0.8146]],

        [[0.2992, 0.8918, 0.0772, 0.8908],
         [0.2604, 0.3018, 0.9255, 0.8316],
         [0.2347, 0.1850, 0.2657, 0.7437]]])


In [12]:
# Create int array from a given range, of a given size

i1 = torch.randint(6, 10, (5,))  # 10 is excluded
print(i1.dtype, i1)

i2 = torch.randint(6, 10, (2,3))
print(i2.dtype, i2)

torch.int64 tensor([8, 6, 7, 7, 6])
torch.int64 tensor([[7, 8, 6],
        [8, 8, 9]])


In [13]:
# Create a Zeros matrix

z = torch.zeros(2, 3)
print(z)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [14]:
# Create a Ones matrix

o = torch.ones(2, 3)
print(o)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [15]:
# Create a tensor like the size of another tensor, of a give data type

r2_la = torch.rand_like(r2, dtype=torch.double)
print(r2_la)

tensor([[0.4201, 0.9795, 0.5203, 0.6747],
        [0.4176, 0.6005, 0.4882, 0.9816],
        [0.9837, 0.7291, 0.6752, 0.9573]], dtype=torch.float64)


## 5. Slicing tensors

In [16]:
rs = torch.rand(3, 3)
print(rs)

# All row, col index 1
rs1 = rs[:,1]
print(rs1, rs1.shape)

# All row, col index 1 while keeping the "shape"
rs2 = rs[:,1:2]
print(rs2, rs2.shape)


# All col, row index 2
print(rs[2,:])

# Row index 1-2, col index 0-1
print(rs[1:, :2])

tensor([[0.2603, 0.0609, 0.7094],
        [0.6899, 0.2892, 0.8653],
        [0.3204, 0.0861, 0.7744]])
tensor([0.0609, 0.2892, 0.0861]) torch.Size([3])
tensor([[0.0609],
        [0.2892],
        [0.0861]]) torch.Size([3, 1])
tensor([0.3204, 0.0861, 0.7744])
tensor([[0.6899, 0.2892],
        [0.3204, 0.0861]])


## 6. Extracting element

In [17]:
# Pick up a tensor element
rs_tensor = rs[1,1]
print(rs_tensor)

# Extract number out of that tensor
rs_number = rs_tensor.item()
print(rs_number)

tensor(0.2892)
0.28918391466140747


## 7. NumPy - PyTorch - List interconversion

In [18]:
# Make list
l_a = [1, 2, 3]
l_b = [[1, 2], [3, 4]]

print(l_a, type(l_a))
print(l_b, type(l_b))

# Convert list to tensor
t_a = torch.tensor(l_a)
t_b = torch.tensor(l_b)

print(t_a, type(t_a))
print(t_b, type(t_b))

# Convert tensor to numpy
n_a = t_a.numpy()
n_b = t_b.numpy()

print(n_a, type(n_a))
print(n_b, type(n_b))

# Convert numpy to tensor
t2_a = torch.from_numpy(n_a)
t2_b = torch.from_numpy(n_b)

print(t2_a, type(t2_a))
print(t2_b, type(t2_b))

# Convert tensor to list
l2_a = t2_a.tolist()
l2_b = t2_b.tolist()

print(l2_a, type(l2_a))
print(l2_b, type(l2_b))

[1, 2, 3] <class 'list'>
[[1, 2], [3, 4]] <class 'list'>
tensor([1, 2, 3]) <class 'torch.Tensor'>
tensor([[1, 2],
        [3, 4]]) <class 'torch.Tensor'>
[1 2 3] <class 'numpy.ndarray'>
[[1 2]
 [3 4]] <class 'numpy.ndarray'>
tensor([1, 2, 3]) <class 'torch.Tensor'>
tensor([[1, 2],
        [3, 4]]) <class 'torch.Tensor'>
[1, 2, 3] <class 'list'>
[[1, 2], [3, 4]] <class 'list'>


## 8. Tensor concatenation

In [19]:
# Row concatenation of tensors - concat alson dim 0
# Size must match in all except dim 0

ft1 = torch.randn(2, 5)
ft2 = torch.randn(3, 5)

print("IP tensor 1 \n", ft1)
print("IP tensor 2 \n", ft2)

fr = torch.cat([ft1, ft2])
print("OP tensor \n", fr)

IP tensor 1 
 tensor([[-0.1069, -0.5393,  0.3637, -1.2491,  0.5409],
        [-0.6241, -0.1017,  0.9806,  0.5713, -0.3293]])
IP tensor 2 
 tensor([[-1.7968, -0.8417,  1.3281,  0.5404,  0.9872],
        [ 0.3730,  0.1417,  1.5819,  0.3763, -0.1709],
        [-1.5795,  0.4513, -0.5372,  0.6090, -0.0854]])
OP tensor 
 tensor([[-0.1069, -0.5393,  0.3637, -1.2491,  0.5409],
        [-0.6241, -0.1017,  0.9806,  0.5713, -0.3293],
        [-1.7968, -0.8417,  1.3281,  0.5404,  0.9872],
        [ 0.3730,  0.1417,  1.5819,  0.3763, -0.1709],
        [-1.5795,  0.4513, -0.5372,  0.6090, -0.0854]])


In [20]:
# Column concatenation of tensors - concat alson dim 1
# Size must match in all except dim 1
st1 = torch.randn(4, 3)
st2 = torch.randn(4, 2)

print("IP tensor 1 \n", st1)
print("IP tensor 2 \n", st2)

sr = torch.cat([st1, st2], 1)
print("OP tensor \n", sr)

IP tensor 1 
 tensor([[ 0.0705, -0.6250, -0.0855],
        [-1.4911, -0.2035, -0.2937],
        [ 1.6193,  1.2257,  1.0012],
        [-0.3547,  0.2732, -0.8293]])
IP tensor 2 
 tensor([[ 0.2552, -1.4264],
        [ 2.3718, -0.0513],
        [ 0.4184, -0.1394],
        [-1.0603,  1.9741]])
OP tensor 
 tensor([[ 0.0705, -0.6250, -0.0855,  0.2552, -1.4264],
        [-1.4911, -0.2035, -0.2937,  2.3718, -0.0513],
        [ 1.6193,  1.2257,  1.0012,  0.4184, -0.1394],
        [-0.3547,  0.2732, -0.8293, -1.0603,  1.9741]])


## 9. Tensor dimension manipulation

In [31]:
# Unsqueeze tensor i.e. add 1 more dimension
# within the range of current dimensions

# 1D tensor
t1 = torch.rand(3)
print(t1, t1.shape)

t1s0 = torch.unsqueeze(t1, 0)
print(t1s0, t1s0.shape)

t1s1 = torch.unsqueeze(t1, 1)
print(t1s1, t1s1.shape)

print("\n")

# 2D tensor
t2 = torch.rand(2,3)
print(t2, t2.shape)

t2s0 = torch.unsqueeze(t2, 0)
print(t2s0, t2s0.shape)

t2s1 = torch.unsqueeze(t2, 1)
print(t2s1, t2s1.shape)

t2s2 = torch.unsqueeze(t2, 2)
print(t2s2, t2s2.shape)

tensor([0.9844, 0.1049, 0.8358]) torch.Size([3])
tensor([[0.9844, 0.1049, 0.8358]]) torch.Size([1, 3])
tensor([[0.9844],
        [0.1049],
        [0.8358]]) torch.Size([3, 1])


tensor([[0.1895, 0.6965, 0.0510],
        [0.8315, 0.9958, 0.4457]]) torch.Size([2, 3])
tensor([[[0.1895, 0.6965, 0.0510],
         [0.8315, 0.9958, 0.4457]]]) torch.Size([1, 2, 3])
tensor([[[0.1895, 0.6965, 0.0510]],

        [[0.8315, 0.9958, 0.4457]]]) torch.Size([2, 1, 3])
tensor([[[0.1895],
         [0.6965],
         [0.0510]],

        [[0.8315],
         [0.9958],
         [0.4457]]]) torch.Size([2, 3, 1])


In [34]:
# Squeeze tensor i.e. remove dimension of size 1
# else leave it unchanged

t2s1u = torch.squeeze(t2s1)
print(t2s1u, t2s1u.shape)

t2s1u0 = torch.squeeze(t2s1, 0)
print(t2s1u0, t2s1u0.shape)

t2s1u1 = torch.squeeze(t2s1, 1)
print(t2s1u1, t2s1u1.shape)

t2s1u2 = torch.squeeze(t2s1, 2)
print(t2s1u2, t2s1u2.shape)


tensor([[0.1895, 0.6965, 0.0510],
        [0.8315, 0.9958, 0.4457]]) torch.Size([2, 3])
tensor([[[0.1895, 0.6965, 0.0510]],

        [[0.8315, 0.9958, 0.4457]]]) torch.Size([2, 1, 3])
tensor([[0.1895, 0.6965, 0.0510],
        [0.8315, 0.9958, 0.4457]]) torch.Size([2, 3])
tensor([[[0.1895, 0.6965, 0.0510]],

        [[0.8315, 0.9958, 0.4457]]]) torch.Size([2, 1, 3])
