# Basic PyTorch

## 1. Import and use

In [2]:
# Import Toch and check version

import torch

print(torch.__version__)

1.4.0+cpu


## 2. Create tensors

In [4]:
# Create 1D tensor

a = torch.tensor([2, 2, 1])
print(a)

tensor([2, 2, 1])


In [14]:
# Create 2D tensor

b = torch.tensor([
    [2, 1, 4],
    [3, 5, 4],
    [1, 2, 0],
    [4, 3, 2]
    ])

print(b)

tensor([[2, 1, 4],
        [3, 5, 4],
        [1, 2, 0],
        [4, 3, 2]])


In [25]:
# Making tensors withnon-integer real numbers
# setting dtype = float or double
c = torch.tensor([
    [2, 1, 4],
    [3, 5, 4],
    [1, 2, 0],
    [4, 3, 2]
    ], dtype=torch.float)

print(c, c.dtype)

tensor([[2., 1., 4.],
        [3., 5., 4.],
        [1., 2., 0.],
        [4., 3., 2.]]) torch.float32


## 3. Play with shape and size

In [15]:
# Size and shape of tensors

print("Size and shape of a: ", a.size(), " ", a.shape)
print("Size and shape of b: ", b.size(), " ", b.shape)

Size and shape of a:  torch.Size([3])   torch.Size([3])
Size and shape of b:  torch.Size([4, 3])   torch.Size([4, 3])


In [16]:
# Rows and columns in a tensor

print("Rows and columns of b: ", b.shape[0], " ", b.shape[1])

Rows and columns of b:  4   3


In [24]:
# Reshaping array

b1 = b.view(-1, 2)  # Auto infer row, col = 2
print("b1(?, 2)", b1)

b2 = b.view(-1)  # Make no row, auto infer col 
print("b2(?)", b2) 

b3 = b.view(1, -1)  # Make 1 row, auto infer col
print("b3(1, ?)", b3) 

b4 = b.view(-1, 1)  # Auto infer row, col = 1
print("b4(?, 1)", b4) 

b1(?, 2) tensor([[2, 1],
        [4, 3],
        [5, 4],
        [1, 2],
        [0, 4],
        [3, 2]])
b2(?) tensor([2, 1, 4, 3, 5, 4, 1, 2, 0, 4, 3, 2])
b3(1, ?) tensor([[2, 1, 4, 3, 5, 4, 1, 2, 0, 4, 3, 2]])
b4(?, 1) tensor([[2],
        [1],
        [4],
        [3],
        [5],
        [4],
        [1],
        [2],
        [0],
        [4],
        [3],
        [2]])


## 4. Make tensors of specific type