# Basic PyTorch

## 1. Import and use

In [ ]:
# Import Toch and check version

import torch
print(torch.__version__)

import numpy as np
print(np.__version__)


## 2. Create tensors

In [ ]:
# Create 1D tensor

a = torch.tensor([2, 2, 1])
print(a)

In [ ]:
# Create 2D tensor

b = torch.tensor([
    [2, 1, 4],
    [3, 5, 4],
    [1, 2, 0],
    [4, 3, 2]
    ])

print(b)

In [ ]:
# Making tensors withnon-integer real numbers
# setting dtype = float or double
c = torch.tensor([
    [2, 1, 4],
    [3, 5, 4],
    [1, 2, 0],
    [4, 3, 2]
    ], dtype=torch.float)

print(c, c.dtype)

## 3. Play with shape and size

In [ ]:
# Size and shape of tensors

print("Size and shape of a: ", a.size(), " ", a.shape)
print("Size and shape of b: ", b.size(), " ", b.shape)

In [ ]:
# Rows and columns in a tensor

print("Rows and columns of b: ", b.shape[0], " ", b.shape[1])

In [ ]:
# Reshaping array

b1 = b.view(-1, 2)  # Auto infer row, col = 2
print("b1(?, 2)", b1)

b2 = b.view(-1)  # Make no row, auto infer col 
print("b2(?)", b2) 

b3 = b.view(1, -1)  # Make 1 row, auto infer col
print("b3(1, ?)", b3) 

b4 = b.view(-1, 1)  # Auto infer row, col = 1
print("b4(?, 1)", b4) 

## 4. Make tensors of specific type

In [ ]:
# Create a random 2D tensor

r1 = torch.rand(3, 4)
print(r1.dtype, r1)

In [ ]:
# Create a random 2D tensor from a N(0,1)

r2 = torch.rand(3, 4)
print(r2.dtype, r2)

In [ ]:
# Create a random 3D tensor from a N(0,1)

r3 = torch.rand(2, 3, 4)
print(r3.dtype, r3)

In [ ]:
# Create int array from a given range, of a given size

i1 = torch.randint(6, 10, (5,))  # 10 is excluded
print(i1.dtype, i1)

i2 = torch.randint(6, 10, (2,3))
print(i2.dtype, i2)

In [ ]:
# Create a Zeros matrix

z = torch.zeros(2, 3)
print(z)

In [ ]:
# Create a Ones matrix

o = torch.ones(2, 3)
print(o)

In [ ]:
# Create a tensor like the size of another tensor, of a give data type

r2_la = torch.rand_like(r2, dtype=torch.double)
print(r2_la)

## 5. Slicing tensors

In [ ]:
rs = torch.rand(3, 3)
print(rs)

# All row, col index 1
rs1 = rs[:,1]
print(rs1, rs1.shape)

# All row, col index 1 while keeping the "shape"
rs2 = rs[:,1:2]
print(rs2, rs2.shape)


# All col, row index 2
print(rs[2,:])

# Row index 1-2, col index 0-1
print(rs[1:, :2])

## 6. Extracting element

In [ ]:
# Pick up a tensor element
rs_tensor = rs[1,1]
print(rs_tensor)

# Extract number out of that tensor
rs_number = rs_tensor.item()
print(rs_number)

## 7. NumPy - PyTorch - List interconversion

In [ ]:
# Make list
l_a = [1, 2, 3]
l_b = [[1, 2], [3, 4]]

print(l_a, type(l_a))
print(l_b, type(l_b))

# Convert list to tensor
t_a = torch.tensor(l_a)
t_b = torch.tensor(l_b)

print(t_a, type(t_a))
print(t_b, type(t_b))

# Convert tensor to numpy
n_a = t_a.numpy()
n_b = t_b.numpy()

print(n_a, type(n_a))
print(n_b, type(n_b))

# Convert numpy to tensor
t2_a = torch.from_numpy(n_a)
t2_b = torch.from_numpy(n_b)

print(t2_a, type(t2_a))
print(t2_b, type(t2_b))

# Convert tensor to list
l2_a = t2_a.tolist()
l2_b = t2_b.tolist()

print(l2_a, type(l2_a))
print(l2_b, type(l2_b))

## 8. Tensor concatenation

In [ ]:
# Row concatenation of tensors - concat alson dim 0
# Size must match in all except dim 0

ft1 = torch.randn(2, 5)
ft2 = torch.randn(3, 5)

print("IP tensor 1 \n", ft1)
print("IP tensor 2 \n", ft2)

fr = torch.cat([ft1, ft2])
print("OP tensor \n", fr)

In [ ]:
# Column concatenation of tensors - concat alson dim 1
# Size must match in all except dim 1
st1 = torch.randn(4, 3)
st2 = torch.randn(4, 2)

print("IP tensor 1 \n", st1)
print("IP tensor 2 \n", st2)

sr = torch.cat([st1, st2], 1)
print("OP tensor \n", sr)

## 9. Tensor dimension manipulation

In [ ]:
# Unsqueeze tensor i.e. add 1 more dimension
# within the range of current dimensions

# 1D tensor
t1 = torch.rand(3)
print(t1, t1.shape)

t1s0 = torch.unsqueeze(t1, 0)
print(t1s0, t1s0.shape)

t1s1 = torch.unsqueeze(t1, 1)
print(t1s1, t1s1.shape)

print("\n")

# 2D tensor
t2 = torch.rand(2,3)
print(t2, t2.shape)

t2s0 = torch.unsqueeze(t2, 0)
print(t2s0, t2s0.shape)

t2s1 = torch.unsqueeze(t2, 1)
print(t2s1, t2s1.shape)

t2s2 = torch.unsqueeze(t2, 2)
print(t2s2, t2s2.shape)

In [ ]:
# Squeeze tensor i.e. remove dimension of size 1
# else leave it unchanged

t2s1u = torch.squeeze(t2s1)
print(t2s1u, t2s1u.shape)

t2s1u0 = torch.squeeze(t2s1, 0)
print(t2s1u0, t2s1u0.shape)

t2s1u1 = torch.squeeze(t2s1, 1)
print(t2s1u1, t2s1u1.shape)

t2s1u2 = torch.squeeze(t2s1, 2)
print(t2s1u2, t2s1u2.shape)


## 10. Autograd

In [37]:
# Without grad = True

x1 = torch.tensor([1., 2., 3.])
x2 = torch.tensor([4., 5., 6.])

y = x1 + x2
print(y, y.grad_fn)

z = y.sum()
print(z, z.grad_fn)

tensor([5., 7., 9.]) None
tensor(21.) None


In [38]:
# With grad = True on all inputs

x1 = torch.tensor([1., 2., 3.], requires_grad=True)
x2 = torch.tensor([4., 5., 6.], requires_grad=True)

y = x1 + x2
print(y, y.grad_fn)

z = y.sum()
print(z, z.grad_fn)

tensor([5., 7., 9.], grad_fn=<AddBackward0>) <AddBackward0 object at 0x7f661cc2a6a0>
tensor(21., grad_fn=<SumBackward0>) <SumBackward0 object at 0x7f661cc2a6a0>


In [39]:
# With grad = True, but not on all inputs

x1 = torch.tensor([1., 2., 3.])
x2 = torch.tensor([4., 5., 6.], requires_grad=True)

y = x1 + x2
print(y, y.grad_fn)

z = y.sum()
print(z, z.grad_fn)

tensor([5., 7., 9.], grad_fn=<AddBackward0>) <AddBackward0 object at 0x7f661cc2aee0>
tensor(21., grad_fn=<SumBackward0>) <SumBackward0 object at 0x7f661cc2aee0>


In [43]:
# Autograd enabling and disabling

x = torch.tensor([1., 2., 3.])
print(x.requires_grad)

x.requires_grad_()
print(x.requires_grad)

# Discarding history and grad functionality of a tensor into a new tensor

x_det = x.detach()
print(x_det.requires_grad)

# Perform operation with autograd disabled

with torch.no_grad():
    print(x.requires_grad)

False
True
False
True


In [52]:
# Perform backward gradient calculation

x = torch.ones(2, 2, requires_grad=True)
print(x)

y = x + 2
print(y)

z = 3 * y ** 2
print(z)

o = z.mean()
print(o)

o.backward()

print(z.grad)
print(y.grad)
print(x.grad)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
tensor(27., grad_fn=<MeanBackward0>)
None
None
tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])
